### ISSUE TITLE
[RFC]: Arquiteturas de tabelas dentro do Git Workflow

### ISSUE THREAD

**Issue by aspeddro** [basedosdados/pipelines#1115]
## Resumo

> Esse RFC é só para capturar a impressão de vocês, os detalhes de implementação como: qual nome do arquivo, o schema do yaml vai ser discutido depois.

Atualmente a gente salva a arquitetura de uma tabela no Drive em um Google Sheet. Esse sheet é compartilhado com a equipe de dados para revisar.

Google Sheet é prático e o conceito de tabela é fácil para qualquer um entender, já temos um template pronto. 

## Proposta

Manter todo o processo de revisão dentro do Git workflow, a nível de pull request como era feito no antigo repo `mais` , agora `sdk`

Um arquivo YAML pode substituir a planilha, [exemplo](https://github.com/basedosdados/sdk/blob/f99a047e0516bfc0b32714aa01496ab577c7bb92/bases/br_abrinq_oca/municipio_primeira_infancia/table_config.yaml#L110-L200)

> Esse exemplo não é o formato proposto. Apenas mostrando que podemos representar as mesmas informações no Google Sheet em um arquivo YAML

```yaml
columns:
    - name: ano
      bigquery_type: int64
      description: Ano
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_data_tempo
          table_id: ano
          column_name: ano
      measurement_unit: year
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
    - name: id_municipio
      bigquery_type: string
      description: ID Município - IBGE 7 Dígitos
      temporal_coverage:
          - (1)
      covered_by_dictionary: no
      directory_column:
          dataset_id: br_bd_diretorios_brasil
          table_id: municipio
          column_name: id_municipio
      measurement_unit:
      has_sensitive_data: no
      observations:
      is_in_staging: true
      is_partition: false
```

## Problemas de salvar no Drive

- Um pessoa pode alterar sem querer a planilha ou deletar. Já encontrei tabelas no BigQuery que não tinha uma arquitetura salva no Drive.
- Não está claro como um contribuidor externo adicionar a arquitetura no nosso Drive.
    - Ele compartilha o link e revisamos, mas depois ele adiciona ou alguém é responsável por adicionar?

## Benefícios

- YAML é um formato de arquivo e tem suporte nativo para boolean, integer, float, string, date, collections (equivalente a dict em python), sequences (equivalente a listas em python)
- Usamos a planilha de arquitetura para subir as colunas e criar o `schema.yml` para o DBT, acho que com essa proposta podemos simplificar um pouco o processo
- Alguma integração no CI (GitHub Actions) para pegar erros pode ser adicionado
- Uma parte do processo de subida de novos dados é criar o dataset e tabelas em https://backend.basedosdados.org/admin/. Podemos fazer isso automaticamente ao mesclar um PR.

## Contras

- Contribuidores podem ter dificuldade para entender o formato YAML

Fiquem a vontade para adicionar mais pontos que vocês consideram contra.
